#!/bin/bash --norc

binary=tigerc.x86-linux
lexer=tiger.lex.sml
rlexer=rescue-$lexer
id='>>> This is rescue-tiger.lex.sml <<<'

if strings $binary | grep "$id" >/dev/null; then
    isRescue="yes"; unset isGenerated
else
    isGenerated="yes"; unset isRescue
fi

case $1 in
    (generated)
        if [ "$isRescue" = "yes" ]; then
            echo "Removing compiler using rescue lexer"
            chmod u+w $binary $lexer
            rm -f $binary $lexer
        fi;;
    (rescue)
        if [ "$isGenerated" = "yes" ]; then
            echo "Removing compiler not using rescue lexer"
            chmod u+w $binary $lexer
            rm -f $binary $lexer
            cp $rlexer $lexer
            touch $lexer
        fi;;
esac

